CREATE TABLE `smarthome`.`fakedatas` (
  `sensing_dt` DATETIME NOT NULL,
  `pub_id` VARCHAR(10) NOT NULL,
  `count` DECIMAL NOT NULL,
  `temp` DECIMAL(5,1) NOT NULL,
  `humid` DECIMAL(5,1) NOT NULL,
  `light` CHAR(1) NOT NULL,
  `human` CHAR(1) NOT NULL,
  PRIMARY KEY (`sensing_dt`, `pub_id`));